name: casp_rna_em
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - biopandas
  - pip:
    - BioTEMPy==2.0.0 
    - rna-tools
