name: casp_rna_em
channels:
  - conda-forge
  - defaults
dependencies:
  - biopandas=0.4.1
  - jupyter=1.0.0
  - jupyterlab=3.6.3
  - matplotlib=3.7.1
  - numpy=1.24.2
  - pandas=2.0.0
  - pillow=9.4.0
  - pip=23.0.1
  - python=3.10.10
  - scipy=1.10.0
  - seaborn=0.12.2
  - pip:
    - biopython==1.73
    - biotempy==2.0.0
    - mrcfile==1.4.3
    - progressbar2==4.2.0
    - pyfftw==0.13.1
    - rna-tools==3.12.1
    - tqdm==4.65.0
